 INSERT * INTO TABLE Sales (
  id SERIAL PRIMARY KEY,
  date TIMESTAMP NOT NULL,
  lastChangeDate TIMESTAMP NOT NULL,
  warehouseName VARCHAR(255),
  countryName VARCHAR(255),
  oblastOkrugName VARCHAR(255),
  regionName VARCHAR(255),
  supplierArticle VARCHAR(50),
  nmId BIGINT,
  barcode VARCHAR(50),
  category VARCHAR(255),
  subject VARCHAR(255),
  brand VARCHAR(255),
  techSize VARCHAR(50),
  incomeID BIGINT,
  isSupply BOOLEAN,
  isRealization BOOLEAN,
  totalPrice FLOAT,
  discountPercent INT,
  spp FLOAT,
  paymentSaleAmount FLOAT,
  forPay FLOAT,
  finishedPrice FLOAT,
  priceWithDisc FLOAT,
  saleID VARCHAR(50),
  orderType VARCHAR(255),
  sticker VARCHAR(255),
  gNumber VARCHAR(255),
  srid VARCHAR(255)
);
